config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  root "pages#home"
  get "konectedna" => "pages#konectedna"
  get "ponedeljek0610" => "pages#ponedeljek0610"
  get "torek0710" => "pages#torek0710"
  get "sreda0810" => "pages#sreda0810"
  get "cetrtek0910" => "pages#cetrtek0910"
  get "petek1010" => "pages#petek1010"
  get "ponedeljek1310" => "pages#ponedeljek1310"
  get "praznastran" => "pages#praznastran"
  get "torek1410" => "pages#torek1410"
  get "sreda1510" => "pages#sreda1510"
  get "cetrtek1610" => "pages#cetrtek1610"
  get "petek1710" => "pages#petek1710"
  get "petek2410" => "pages#petek2410"
  get "sobota2510" => "pages#sobota2510"
  get "torek2810" => "pages#torek2810"
  get "sreda2910" => "pages#sreda2910"
  get "sobota0111" => "pages#sobota0111"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def konectedna
  end
  def ponedeljek0610
  end
  def torek0710
  end
  def sreda0810
  end
  def cetrtek0910
  end
  def petek1010
  end
  def ponedeljek1310
  end
  def praznastran
  end
  def torek1410
  end
  def sreda1510
  end
  def cetrtek1610
  end
  def petek1710
  end
  def petek2410
  end
  def sobota2510
  end
  def torek2810
  end
  def sreda2910
  end
  def sobota0111
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Carlo" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/cetrtek0910.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carlo Acutis</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=My+Soul&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Playwrite+VN+Guides&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Smooch+Sans:wght@100..900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Cursive:wght@400..700&family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</head>
<body>
    <div class="container6">
        <h1>Četrtek</h1>
        <h4>9. oktober</h4>
        <p>Zdajle imam kar dosti časa zdajle, ki bi ga lahko namenil programiranju, saj sem zgodaj začel z dnevom.</p>
        <p>A čutim tudi svojo nesposobnost, in me je strah, da bi se zapletel v težave, ki jih nebi mogel rešiti.</p>
        <div class="container6">
            <%= image_tag "troubles.jpg", alt: "troubles" %>
        </div>
        <p>Saj meni bi že veliko pomenilo, če bi se vsaj kolikor toliko redno usedel za računalnik.</p>
        <p>Pa četudi bi samo nekaj malega napravil.</p>
        <p>In me nebi premagala strah in odpor.</p>
        <br>
        <p>Potemtakem bi morda kdaj na dolgi rok lahko kaj nastalo.</p>
        <p>Brez, da bi jaz večino časa sploh vedel kam to pelje.</p>
        <div class="container6">
            <%= image_tag "neznano.jpg", alt: "Neznanokam" %>
        </div>
        <p>Tako zelo težko je živeti v tem svetu polnem nevarnosti.</p>
        <div class="container6">
            <%= image_tag "danger.jpg", alt: "danger" %>
        </div>
        <p>Ne zdi se, da je karkoli pravično.</p>
        <div class="container6">
            <%= image_tag "blind.jpg", alt: "unfair" %>
        </div>
        <p>Ah, ne vem kako bo. Prosim usmiljenja.</p>
    </div>
    <div class="container5">
         <p id="sredina">
            <a href="./">
                <button class="button">
                    <i class="bi bi-house-fill" style="font-size: 1.5rem;"></i>
                </button>
            </a>
        </p>
    </div>
</body>
</html>

app/views/pages/cetrtek1610.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carlo Acutis</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=My+Soul&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Playwrite+VN+Guides&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Smooch+Sans:wght@100..900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Cursive:wght@400..700&family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</head>
<body>
    <div class="container6">
        <h1>Četrtek</h1>
        <h4>16. oktober</h4>
        <p>Pred programiranjem sem nazadnje prebral 4 vprašanja v Summi Theologici.</p>
        <div class="container6">
            <%= image_tag "summa.jpg", alt: "summa theologica." %>
        </div>
        <p>Sem vesel, da še vedno vztrajam, ali pa znova vztrajam, v tem nespametnem početju zaradi katerega me boli glava.</p>
        <hr>
        <p>Še pred tem sem pa prebral poglavje Dialogo della Divina Provvidenzia.</p>
        <%= image_tag "dialogo.jpg", alt: "dialogo" %>
        <hr>
        <p>Sem pa nasplošno zelo žalosten in zelo osamljen.</p>
        <p>Najrajše bi umrl in šel s tega hudobnega sveta, v katerem ne znam in ne zmorem delati dobro.</p>
        <p>Drugi ljudje so mnogo boljši, stalno delajo družbene koristne stvari, jaz pa ničesar ne.</p>
        <br>
    </div>
    <div class="container5">
        <p>Zelo mi je težko.</p>
    </div>
    <div class="container6">
        <br>
        <p>Mislim, da danes ne bom kaj preveč programiral, da je to dovolj.</p>
    </div>
        <div class="container5">
         <p id="sredina">
            <a href="./sreda1510">
                 <button class="button">
                    <i class="bi bi-arrow-left-circle" style="font-size: 1.5rem;"></i>
                 </button>
            </a>
            <a href="./">
                <button class="button">
                    <i class="bi bi-house-fill" style="font-size: 1.5rem;"></i>
                </button>
            </a>
            <a href="./praznastran">
                 <button class="button">
                    <i class="bi bi-arrow-right-circle" style="font-size: 1.5rem;"></i>
                </button>
            </a>
        </p>
    </div>
</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carlo Acutis</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=My+Soul&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Playwrite+VN+Guides&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Smooch+Sans:wght@100..900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Cursive:wght@400..700&family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</head>
<body>
    <div class="container6">
        <h1>Carlo Acutis</h1>
        <%= image_tag "Carlo.webp", alt: "Carlo" %>
        <p>Ta stran je posvečena Carlu Acutisu, na katerega priprošnjo se tudi obračam.</p>
    </div>
    <div class="container3">
        <ul>
          <p id="poudarjeno">Tu bom probal dodajati linke do poizkusnih strani.</p>
            <li>
                <p>Tukaj je za</p>
                <a href="./konectedna">
                    <button class="button">zadnji dan</button>
                </a>
                <p>V tem tednu</p>
            </li>
        </ul>
    </div>
    <div class="container3">
        <ul>
          <p id="poudarjeno">Saj zdaj je že nov teden.</p>
          <p>Začnimo s</p>
            <li>
                <a href="./ponedeljek0610">
                    <button class="button">ponedeljkom</button>
                </a>
            </li>
          <p>Nadaljujemo pa že s</p>
            <li>
                <a href="./torek0710">
                    <button class="button">torkom</button>
                </a>
            </li>
          <p>In kar naenkrat je tu</p>
            <li>
                <a href="./sreda0810">
                    <button class="button">sreda</button>
                </a>
            </li>
          <p>Kdo bi si mislil, da bom programiral tudi v</p>
            <li>
                <a href="./cetrtek0910">
                    <button class="button">četrtek</button>
                </a>
            </li>
          <p>Zdaj pa sem tukaj še v</p>
            <li>
                <a href="./petek1010">
                    <button class="button">petek</button>
                </a>
            </li>

        </ul>
      </div>
       <div class="container3">
        <ul>
          <p id="poudarjeno">Začetek novega tedna.</p>
            <li>
                <a href="./ponedeljek1310">
                    <button class="button">Prva stran</button>
                </a>
                <p>novega tedna</p>
            </li>
            <li>
                <a href="./torek1410">
                    <button class="button">Druga stran</button>
                </a>
            </li>
            <li>
                <a href="./sreda1510">
                    <button class="button">3. stran</button>
                </a>
            </li>
            <li>
                <p>Izgleda, da bo uspela še</p>
                <a href="./cetrtek1610">
                    <button class="button">4. stran</button>
                </a>
            </li>
            <li>
                <p>To bo pa najverjetneje</p>
                <a href="./petek1710">
                    <button class="button">Zadnja stran</button>
                </a>
                <p>v tem tednu</p>
            </li>
            <hr>
            <a href="./petek1710">
                <%= image_tag "finish.jpg", alt: "finish" %>
            </a>
        </ul>
        </div>
        <div class="container3">
            <ul>
            <p id="poudarjeno">V tem tednu</p>
             <p>pa prvič (in morda zadnjič) programiram šele v:</p>
                <li>
                    <a href="./petek2410">
                        <button class="button">petek</button>
                    </a>
                </li>
            <p>Bo po izgleda uspelo še</p>
                <li>
                    <a href="./sobota2510">
                        <button class="button">drugič</button>
                    </a>
                </li>
            <p>v tem tednu.</p>
            <hr>
            <a href="./sobota2510">
                <%= image_tag "ograja.jpg", alt: "finish" %>
            </a>
            </ul>
        </div>
        <div class="container3">
            <ul>
            <p id="poudarjeno">V tem tednu</p>
             <p>pa prvič programiram v:</p>
                <li>
                    <a href="./torek2810">
                        <button class="button">torek</button>
                    </a>
                </li>
            <p>Kar je sicer boljše kot v petek, a zelo obžalujem, da nisem rajše začel že včeraj.</p>
            <hr>
            <p>Nadaljujem pa že v:</p>
                <li>
                    <a href="./sreda2910">
                        <button class="button">sredo</button>
                    </a>
                </li>
            <p>Končujem pa v:</p>
                <li>
                    <a href="./sobota0111">
                        <button class="button">soboto</button>
                    </a>
                </li>
            </ul>
        </div>
    </div>
    
</body>
</html>

app/views/pages/konectedna.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carlo Acutis</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=My+Soul&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Playwrite+VN+Guides&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Smooch+Sans:wght@100..900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Cursive:wght@400..700&family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</head>
<body>
    <div class="container6">
        <h1>Konec tedna</h1>
        <p>Ta teden je bil precej težak zame.</p>
        <p>Počutim se, da sem primeren le še za odstrel.</p>
        <p>Zelo sem osamljen, zares zelo.</p>
        <p>In moj spomin zagotovo ni izpraznjen in podvržen upanju,</p>
        <p>ampak poln obupnih dogodkov.</p>
        <br>
        <p>Na nek način pa sem cel teden preživel skladno z osnovnimi željami,
            po tistem najbolj zahtevnem urniku zame.
        </p>
        <p>Kako je to uspelo, ne vem.</p>
        <p>Gotovo se pa zdi, da so nevarnosti na vsakem koraku.</p>
        <br>
        <p>Vesel sem, da sem žalosten; na koncu tedna žalosten.</p>
        <p>Zdi se skladno z mojimi vrednotami.</p>
        <%= image_tag "noc.jpg", alt: "noc" %>
    </div>
     <div class="container5">
         <p id="sredina">
            <a href="./">
                <button class="button">
                    <i class="bi bi-house-fill" style="font-size: 1.5rem;"></i>
                </button>
            </a>
        </p>
    </div>
</body>
</html>

app/views/pages/ponedeljek0610.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carlo Acutis</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=My+Soul&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Playwrite+VN+Guides&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Smooch+Sans:wght@100..900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Cursive:wght@400..700&family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</head>
<body>
    <div class="container6">
        <h1>Ponedeljek</h1>
        <h4>6. oktober</h4>
        <p>Zdajle sem probal tiste pikce, ki so se pojavile po pleskanju, prebarvat
            in jih nekako napravit za zvezdice.
        </p>
        <%= image_tag "stars.jpg", alt: "zvezdice" %>
        <p>Je še malo prezgodaj za govorit ali je uspelo ali ne.</p>
        <p>Sem pa dodal še nov nanos akrilne barv na dva dela lustra in na vratne podboje.</p>
        <br>
        <p>Saj ni za pričakovat, da bodo stvari na nivoju narejene.</p>
        <p>Bi mi pa dosti pomenilo, če bi se vsaj toliko lotil po malem vzdrževalnih del.</p>
        <p>In bi tako na koncu koncev bile stvari, ki so nekako pod moj skrbjo, vsaj za silo urejene.</p>
        <p>Morda kdaj celo lepe.</p>
        <br>
        <p>Se mi zdi smiselno, da stremim vsaj k osnovnemu dostojnemu življenju.</p>
        <p>Sploh glede na to, da je zame to zelo težko, vsak tak korak šteje.</p>
        <p>In morda se bom tako na dolgi rok še kaj naučil o življenju.</p>
        <br>
        <p>Me pa hitro prične grabit obup pri teh stvareh.</p>
        <p>Pa spomini na ljudi, ki so razvrednotili.</p>
        <p>Ne vem ali je takšno delo neke vrste molitev tudi.</p>
        <p>Ko se ne pusti uničevalni sili zla, da prevlada, ampak se skuša pomalem popraviti škodo udarcev greha.</p>
    </div>
    <div class="container6">
        <p>Mislim, da bo to kar to za danes.</p>
        <p>Važno, da sem lahko začel nov teden. Potem se bo pa že sproti videlo koliko bom zmogel.</p>
        <%= image_tag "start1.jpg", alt: "zacetek" %>
        <%= image_tag "start2.jpg", alt: "pot" %>

    </div>
    <div class="container5">
         <p id="sredina">
            <a href="./">
                <button class="button">
                    <i class="bi bi-house-fill" style="font-size: 1.5rem;"></i>
                </button>
            </a>
        </p>
    </div>
</body>
</html>

app/views/pages/ponedeljek1310.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carlo Acutis</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=My+Soul&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Playwrite+VN+Guides&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Smooch+Sans:wght@100..900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Cursive:wght@400..700&family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</head>
<body>
    <div class="container6">
        <h1>Ponedeljek</h1>
        <h4>13. oktober</h4>
        <p>Danes sem napravil prazno stran, za muštr gumba, ki povezuje prejšnjo z naslednjo stranjo, ki morda še pride.</p>
        <p>Pa barvo gumbov sem spremenil.</p>
        <p>Sem vesel, da sem lahko zaštartal teden.</p>
        <p>Zdaj bom probal le še stran naložiti na strežnik, nato pa zaključiti.</p>
    </div>
        <div class="container5">
         <p id="sredina">
            <a href="./petek1010">
                 <button class="button">
                    <i class="bi bi-arrow-left-circle" style="font-size: 1.5rem;"></i>
                 </button>
            </a>
            <a href="./">
                <button class="button">
                    <i class="bi bi-house-fill" style="font-size: 1.5rem;"></i>
                </button>
            </a>
            <a href="./torek1410">
                 <button class="button">
                    <i class="bi bi-arrow-right-circle" style="font-size: 1.5rem;"></i>
                </button>
            </a>
        </p>
    </div>
</body>
</html>

app/views/pages/praznastran.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carlo Acutis</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta charset="utf-8">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=My+Soul&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Playwrite+VN+Guides&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined" rel="stylesheet" />
  <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Smooch+Sans:wght@100..900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Edu+NSW+ACT+Cursive:wght@400..700&family=Jost:ital,wght@0,100..900;1,100..900&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=EB+Garamond:ital,wght@0,400..800;1,400..800&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400..700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.13.1/font/bootstrap-icons.min.css">
</head>
<body>
    <div class="container6">
        <h1>Prazna stran</h1>
        <h4>Tukaj še ni vsebine</h4>
        <p>Morda pa kdaj v prihodnje bo.</p>
        <p>Če ne bom pozabil ali počel drugih stvari.</p>
        <%= image_tag "workinprogress.jpg", alt: "empty" %>
    </div>
    <div class="container5">
        <p>Se pa najde nekaj vsebine tukaj:</p>
           <p id="sredina">
                <a href="./">
                    <button class="button">
                        <i class="bi bi-house-fill" style="font-size: 1.5rem;"></i>
                    </button>
                </a>
            </p>
    </div>
</body> 
</html>